### ISSUE TITLE
AIS + GPS 

### ISSUE THREAD

**Issue by Tarakona2850** [AK-Homberger/NMEA2000-AIS-Gateway#1]
Hy Andreas.
Super Project! Thanks!

My Comar ais transponder also has a gps sequence. How can position / speed data be translated together with ais lines?
Thanks.
Csaba

**Comment by AK-Homberger** [comment]
Hi Csaba,

In:

```
void ParseAIVDM_Message() {
  int i = 0;

  if (!NMEA0183.GetMessage(NMEA0183Msg)) return;  // New message ?
```

you have to handle, after the NMEA0183.GetMessage function,  the NMEA0183 messages for GPS and create the appropriate NMEA2000 message. That's all.

Regards,
Andreas

**Comment by Tarakona2850** [comment]
it's not that simple. :)

best regards.

Cs

**Comment by AK-Homberger** [comment]
Please have a look to the NMEA2000 workshop: https://github.com/AK-Homberger/NMEA2000-Workshop
It's all explained there.
